language: node_js

node_js:
  - node

before_install:
  - sudo apt-get install graphviz

script:
  - npm run build

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master